db:
  image: mysql:5.7
  volumes:
    - db_data:/var/lib/mysql
  restart: always
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: somewordpress
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: wordpress
    MYSQL_DATABASE: wordpress

wordpress:
  dependes_on:
    -db
  image: wordpress:latest
  restart: always
  ports:
    - "8080:80"
  environment:
    WORDPRESS_DB_HOST: mysql
    WORDPRESS_DB_USER: wordpress
    WORDPRESS_DB_PASSWORD: wordpress
volumes:
  db_data: